//! SeaORM Entity. Generated by sea-orm-codegen 0.9.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "domain")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub userid: i32,
    pub domain: String,
    pub wildcard: i8,
    pub wildcarddomain: Option<String>,
    pub useronly: i8,
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        panic!("No RelationDef")
    }
}

impl ActiveModelBehavior for ActiveModel {}
