//! SeaORM Entity. Generated by sea-orm-codegen 0.9.0

pub use super::config::Entity as Config;
pub use super::domain::Entity as Domain;
pub use super::upload::Entity as Upload;
pub use super::user::Entity as User;
